database:
  host: 10.0.0.1
  port: 3306
  database: xxxx
  username: xxxx
  password: xxxx
  pool_max_conn: 150   #连接池 最大连接
  pool_max_idle: 10    #连接池 最大空闲等待
  pool_idle_time: 120  #空闲最大留存时间，从空闲开始，秒
  pool_life_time: 3600 #连接最大留存时间，从创建开始，秒

redis:
  host: 10.0.0.2
  port: 6379
  password: xxxx
  MaxIdle: 10 #空闲等待连接数
  MaxActive: 800 #最大连接数
  IdleTimeout: 120 #空闲等待时长 秒
  key_prefix: ProjectName_ #可空，redis中存的key前缀，防止多项目共享redis服务key冲突

session:
  name: sessionid #cookie中的session名称
  max_age: 7200 #有效期 秒
  store_key: fiEgyh^4gia#2 #session key

  